---

- name: Install NTP, tzdata
  become: yes
  apt:
    name:
      - ntp
      - tzdata
    state: present

- name: Ensure NTP is running and enabled for SysV
  become: yes
  service:
    enabled: yes
    name: ntp
    state: started
  when: ansible_service_mgr != "systemd"

- name: Ensure timedatectl ntp is off for SystemD
  become: yes
  command: timedatectl set-ntp off
  changed_when: no
  when: ansible_service_mgr == "systemd"

- name: Ensure NTP is running and enabled for SystemD
  become: yes
  systemd:
    enabled: yes
    name: ntp
    state: started
  when: ansible_service_mgr == "systemd"
